//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mold_Inspector.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mold_Inspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Absolute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alram {
            get {
                return ResourceManager.GetString("Alram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C/S과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C_S {
            get {
                return ResourceManager.GetString("C/S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Camera_ID {
            get {
                return ResourceManager.GetString("Camera ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Candidate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Complate {
            get {
                return ResourceManager.GetString("Complate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Current_Recipe {
            get {
                return ResourceManager.GetString("Current Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Columns과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Display_Columns {
            get {
                return ResourceManager.GetString("Display Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Display_Rows {
            get {
                return ResourceManager.GetString("Display Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eject과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eject {
            get {
                return ResourceManager.GetString("Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eject Delay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eject_Delay {
            get {
                return ResourceManager.GetString("Eject Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ejected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ejected {
            get {
                return ResourceManager.GetString("Ejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ejecting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ejecting {
            get {
                return ResourceManager.GetString("Ejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Grab {
            get {
                return ResourceManager.GetString("Grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histogram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inflate Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Inflate_Height {
            get {
                return ResourceManager.GetString("Inflate Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inflate Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Inflate_Width {
            get {
                return ResourceManager.GetString("Inflate Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Inspect {
            get {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ko_KR {
            get {
                return ResourceManager.GetString("ko-KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Live과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lower {
            get {
                return ResourceManager.GetString("Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manufacturer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mold {
            get {
                return ResourceManager.GetString("Mold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orientation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Percentage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prepare과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Prepare {
            get {
                return ResourceManager.GetString("Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Production과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Eject과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Re_Eject {
            get {
                return ResourceManager.GetString("Re-Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Eject Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Re_Eject_Count {
            get {
                return ResourceManager.GetString("Re-Eject Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Robot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Serial_No {
            get {
                return ResourceManager.GetString("Serial No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Upper {
            get {
                return ResourceManager.GetString("Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Ejected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Use_Ejected {
            get {
                return ResourceManager.GetString("Use Ejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Re-Eject과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Use_Re_Eject {
            get {
                return ResourceManager.GetString("Use Re-Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Used_Date {
            get {
                return ResourceManager.GetString("Used Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Fit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zoom_Fit {
            get {
                return ResourceManager.GetString("Zoom Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zoom_In {
            get {
                return ResourceManager.GetString("Zoom In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zoom_Out {
            get {
                return ResourceManager.GetString("Zoom Out", resourceCulture);
            }
        }
    }
}
